-- KumariCinemas Movie Ticketing System - Database Schema (Oracle SQL)

-- 1. Users Table
-- 1. Users Table
CREATE TABLE M_Users (
    UserId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100) NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    Address VARCHAR2(255),
    Role VARCHAR2(20) DEFAULT 'USER',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Username UNIQUE (Username)
);

-- 2. Movies Table (No changes)
CREATE TABLE M_Movies (
    MovieId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(255) NOT NULL,
    Duration VARCHAR2(50), 
    Language VARCHAR2(50),
    Genre VARCHAR2(50),
    ReleaseDate DATE,
    Description CLOB
);

-- 3. Branches (Theater Locations)
CREATE TABLE M_Branches (
    BranchId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BranchName VARCHAR2(100) NOT NULL, 
    Location VARCHAR2(100)
);

-- 4. Halls Table
CREATE TABLE M_Halls (
    HallId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BranchId NUMBER REFERENCES M_Branches(BranchId),
    HallName VARCHAR2(50) NOT NULL,
    Capacity NUMBER NOT NULL CHECK (Capacity > 0)
);

-- 5. Shows Table
CREATE TABLE M_Shows (
    ShowId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MovieId NUMBER REFERENCES M_Movies(MovieId),
    HallId NUMBER REFERENCES M_Halls(HallId),
    ShowDateTime TIMESTAMP NOT NULL, -- Replaces separate Date/Time
    BasePrice NUMBER(10, 2) NOT NULL CHECK (BasePrice >= 0)
);

-- 6. Bookings Table
CREATE TABLE T_Bookings (
    BookingId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId NUMBER REFERENCES M_Users(UserId),
    ShowId NUMBER REFERENCES M_Shows(ShowId),
    BookingTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR2(20) DEFAULT 'BOOKED', 
    FinalPrice NUMBER(10, 2),
    TotalTickets NUMBER DEFAULT 1 CHECK (TotalTickets > 0),
    CONSTRAINT chk_status CHECK (Status IN ('BOOKED', 'PAID', 'CANCELLED'))
);

-- 7. Reviews Table (New Feature)
CREATE TABLE T_Reviews (
    ReviewId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MovieId NUMBER REFERENCES M_Movies(MovieId),
    UserId NUMBER REFERENCES M_Users(UserId),
    Rating NUMBER(2,1) CHECK (Rating BETWEEN 1 AND 5),
    CommentText CLOB,
    ReviewDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Tickets Table (Optional for seat level tracking)
CREATE TABLE T_Tickets (
    TicketId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingId NUMBER REFERENCES T_Bookings(BookingId),
    SeatNumber VARCHAR2(10)
);

-- Sample Data Insertion Scripts will follow after user review
