-- ==========================================
-- KUMARI CINEMAS DATABASE RESET SCRIPT
-- ==========================================
-- This script completely resets the database:
-- 1. Drops all existing tables
-- 2. Recreates the schema
-- 3. Populates with test data
-- ==========================================

SET DEFINE OFF;

-- ---------------------------------------------------------
-- PART 1: DROP EXISTING TABLES (Reverse Dependencies)
-- ---------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_Tickets CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_Reviews CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_Bookings CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE M_Shows CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE M_Halls CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE M_Branches CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE M_Movies CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE M_Users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- ---------------------------------------------------------
-- PART 2: CREATE SCHEMA (From database_schema.sql)
-- ---------------------------------------------------------

-- 1. Users Table
CREATE TABLE M_Users (
    UserId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100) NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    Address VARCHAR2(255),
    Role VARCHAR2(20) DEFAULT 'USER',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Username UNIQUE (Username)
);

-- 2. Movies Table
CREATE TABLE M_Movies (
    MovieId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(255) NOT NULL,
    Duration VARCHAR2(50), 
    Language VARCHAR2(50),
    Genre VARCHAR2(50),
    ReleaseDate DATE,
    Description CLOB,
    ImageUrl VARCHAR2(500)
);

-- 3. Branches (Theater Locations)
CREATE TABLE M_Branches (
    BranchId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BranchName VARCHAR2(100) NOT NULL, 
    Location VARCHAR2(100)
);

-- 4. Halls Table
CREATE TABLE M_Halls (
    HallId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BranchId NUMBER REFERENCES M_Branches(BranchId),
    HallName VARCHAR2(50) NOT NULL,
    Capacity NUMBER NOT NULL CHECK (Capacity > 0)
);

-- 5. Shows Table
CREATE TABLE M_Shows (
    ShowId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MovieId NUMBER REFERENCES M_Movies(MovieId),
    HallId NUMBER REFERENCES M_Halls(HallId),
    ShowDateTime TIMESTAMP NOT NULL,
    BasePrice NUMBER(10, 2) NOT NULL CHECK (BasePrice >= 0)
);

-- 6. Bookings Table
CREATE TABLE T_Bookings (
    BookingId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId NUMBER REFERENCES M_Users(UserId),
    ShowId NUMBER REFERENCES M_Shows(ShowId),
    BookingTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR2(20) DEFAULT 'BOOKED', 
    FinalPrice NUMBER(10, 2),
    TotalTickets NUMBER DEFAULT 1 CHECK (TotalTickets > 0),
    CONSTRAINT chk_status CHECK (Status IN ('BOOKED', 'PAID', 'CANCELLED'))
);

-- 7. Reviews Table
CREATE TABLE T_Reviews (
    ReviewId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MovieId NUMBER REFERENCES M_Movies(MovieId),
    UserId NUMBER REFERENCES M_Users(UserId),
    Rating NUMBER(2,1) CHECK (Rating BETWEEN 1 AND 5),
    CommentText CLOB,
    ReviewDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Tickets Table
CREATE TABLE T_Tickets (
    TicketId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingId NUMBER REFERENCES T_Bookings(BookingId),
    SeatNumber VARCHAR2(10)
);

-- ---------------------------------------------------------
-- PART 3: INSERT TEST DATA (From test_data_3months.sql)
-- ---------------------------------------------------------

-- Add Branches and Halls (Required for Shows)
INSERT INTO M_Branches (BranchName, Location) VALUES ('Kumari Cinemas - Main', 'Downtown');
INSERT INTO M_Branches (BranchName, Location) VALUES ('Kumari Cinemas - East', 'Eastside');

INSERT INTO M_Halls (BranchId, HallName, Capacity) VALUES (1, 'Audi 1', 100);
INSERT INTO M_Halls (BranchId, HallName, Capacity) VALUES (1, 'Audi 2', 120);
INSERT INTO M_Halls (BranchId, HallName, Capacity) VALUES (2, 'Gold Class', 50);

-- Add Fake Movies with Images
INSERT INTO M_Movies (Title, Duration, Language, Genre, ReleaseDate, ImageUrl) 
VALUES ('Interstellar Voyage', '169 min', 'English', 'Fiction', SYSDATE - 10, 
        'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=600&fit=crop');

INSERT INTO M_Movies (Title, Duration, Language, Genre, ReleaseDate, ImageUrl) 
VALUES ('Dragon Warriors', '142 min', 'English', 'Action', SYSDATE - 5,
        'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=600&fit=crop');

INSERT INTO M_Movies (Title, Duration, Language, Genre, ReleaseDate, ImageUrl) 
VALUES ('Laugh Out Loud', '98 min', 'English', 'Comedy', SYSDATE - 3,
        'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop');

INSERT INTO M_Movies (Title, Duration, Language, Genre, ReleaseDate, ImageUrl) 
VALUES ('Midnight Mystery', '127 min', 'English', 'Horror', SYSDATE + 7,
        'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop');

INSERT INTO M_Movies (Title, Duration, Language, Genre, ReleaseDate, ImageUrl) 
VALUES ('Love in Paris', '115 min', 'French', 'Drama', SYSDATE + 14,
        'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop');

COMMIT;

-- Add Shows for Next 3 Months
-- Week 1 (Tomorrow - 7 days from now)
INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (1, 1, SYSDATE + 1 + (10/24), 400);  -- Tomorrow 10 AM

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (2, 2, SYSDATE + 1 + (14/24), 450);  -- Tomorrow 2 PM

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (3, 3, SYSDATE + 2 + (18/24), 350);  -- Day after tomorrow 6 PM

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (1, 1, SYSDATE + 3 + (20/24), 500);  -- 3 days from now 8 PM

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (4, 2, SYSDATE + 4 + (15/24), 420);  -- 4 days from now 3 PM

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (5, 3, SYSDATE + 5 + (19/24), 480);  -- 5 days from now 7 PM

-- Week 2 (8-14 days from now)
INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (2, 1, SYSDATE + 8 + (11/24), 430);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (3, 2, SYSDATE + 9 + (16/24), 380);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (4, 3, SYSDATE + 10 + (13/24), 410);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (5, 1, SYSDATE + 11 + (21/24), 500);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (1, 2, SYSDATE + 12 + (17/24), 460);

-- Week 3-4 (15-30 days from now)
INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (2, 3, SYSDATE + 15 + (12/24), 440);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (3, 1, SYSDATE + 18 + (19/24), 390);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (4, 2, SYSDATE + 21 + (14/24), 420);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (5, 3, SYSDATE + 24 + (20/24), 510);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (1, 1, SYSDATE + 27 + (16/24), 470);

-- Month 2 (30-60 days from now)
INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (2, 2, SYSDATE + 35 + (15/24), 450);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (3, 3, SYSDATE + 40 + (18/24), 400);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (4, 1, SYSDATE + 45 + (13/24), 430);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (5, 2, SYSDATE + 50 + (19/24), 520);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (1, 3, SYSDATE + 55 + (11/24), 410);

-- Month 3 (60-90 days from now)
INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (2, 1, SYSDATE + 65 + (17/24), 460);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (3, 2, SYSDATE + 70 + (14/24), 390);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (4, 3, SYSDATE + 75 + (20/24), 440);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (5, 1, SYSDATE + 80 + (16/24), 530);

INSERT INTO M_Shows (MovieId, HallId, ShowDateTime, BasePrice) 
VALUES (1, 2, SYSDATE + 85 + (12/24), 420);

COMMIT;

-- Re-create ADMIN user (since all users were dropped)
INSERT INTO M_Users (Username, Password, Role) 
VALUES ('admin', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'ADMIN');
-- Password is 'password' hashed

COMMIT;
