using Oracle.ManagedDataAccess.Client;
using System.Data;

namespace KumariCinemas.Web.Services
{
    public class DatabaseInitializer
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<DatabaseInitializer> _logger;

        public DatabaseInitializer(IConfiguration configuration, ILogger<DatabaseInitializer> logger)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public void Initialize()
        {
            try
            {
                string connectionString = _configuration.GetConnectionString("OracleDb");
                using (var connection = new OracleConnection(connectionString))
                {
                    connection.Open();

                    // Check and create T_Watchlist
                    EnsureWatchlistTable(connection);

                    // Check and add missing columns
                    EnsureMovieColumns(connection);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error initializing database.");
                // We don't throw here to avoid stopping the app startup if DB is just down,
                // but in a real app we might want to fail fast.
            }
        }

        private void EnsureWatchlistTable(OracleConnection connection)
        {
            try
            {
                // Check if table exists
                string checkSql = "SELECT COUNT(*) FROM user_tables WHERE table_name = 'T_WATCHLIST'";
                using (var cmd = new OracleCommand(checkSql, connection))
                {
                    int count = Convert.ToInt32(cmd.ExecuteScalar());
                    if (count == 0)
                    {
                        _logger.LogInformation("Creating T_Watchlist table...");
                        string createSql = @"
                            CREATE TABLE T_Watchlist (
                                WatchlistId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                UserId NUMBER REFERENCES M_Users(UserId),
                                MovieId NUMBER REFERENCES M_Movies(MovieId),
                                AddedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT UQ_Watchlist UNIQUE (UserId, MovieId)
                            )";

                        using (var createCmd = new OracleCommand(createSql, connection))
                        {
                            createCmd.ExecuteNonQuery();
                        }
                        _logger.LogInformation("T_Watchlist table created successfully.");
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating T_Watchlist table.");
                throw;
            }
        }

        private void EnsureMovieColumns(OracleConnection connection)
        {
            try
            {
                // Check and add Description
                AddColumnIfNotExists(connection, "M_MOVIES", "DESCRIPTION", "CLOB");
                // Check and add Language
                AddColumnIfNotExists(connection, "M_MOVIES", "LANGUAGE", "VARCHAR2(50)");
                // Check and add Duration
                AddColumnIfNotExists(connection, "M_MOVIES", "DURATION", "VARCHAR2(50)");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating M_Movies columns.");
            }
        }

        private void AddColumnIfNotExists(OracleConnection connection, string tableName, string columnName, string columnType)
        {
            string checkSql = $"SELECT COUNT(*) FROM user_tab_columns WHERE table_name = '{tableName}' AND column_name = '{columnName}'";
            using (var cmd = new OracleCommand(checkSql, connection))
            {
                int count = Convert.ToInt32(cmd.ExecuteScalar());
                if (count == 0)
                {
                    _logger.LogInformation($"Adding column {columnName} to {tableName}...");
                    string alterSql = $"ALTER TABLE {tableName} ADD {columnName} {columnType}";
                    using (var alterCmd = new OracleCommand(alterSql, connection))
                    {
                        alterCmd.ExecuteNonQuery();
                    }
                }
            }
        }
    }
}
